name: ui-beautification
version: 1.0.0
schema: spec-driven
authors:
  - name: User
    email: user@example.com
description: UI美化工作，参考微软ToDo设计风格，提升应用视觉效果
created_at: "2026-02-16"
updated_at: "2026-02-16"
